config/routes.rb
Rails.application.routes.draw do
  authenticate :user, ->(user) { user.admin? } do
    # I recommend adding indents inside all your blocks
    mount RailsAdmin::Engine, at: "/admin", as: "rails_admin"
  end
  
  resources :recipes
  resources :comments
  resources :photos
  resources :marriages
  resources :people
  resources :filials
  resources :contact_forms, only: [:create]
  devise_for :users, controllers: { registrations: "users/registrations" }

  root "welcome#index"
  get '/family_tree' => 'people#tree', as: :tree
  get "/birthdays" => "people#birthdays", as: :birthdays
  get '/contact_us' => 'contact_forms#contact_us', as: :contact
  get "/family/:id" => "people#family", as: :family
  get "/recipes/my_recipes/:id" => "recipes#my_recipes", as: :my_recipes

end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id         :integer          not null, primary key
#  photo_id   :integer
#  body       :text
#  author_id  :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Comment < ApplicationRecord
    belongs_to :author, class_name: "Person", foreign_key: "author_id"
    belongs_to :photo, class_name: "Photo", foreign_key: "photo_id"
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  before_action { authorize(@comment || Comment) }

  # GET /comments or /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1 or /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments or /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to photo_url(@comment.photo), notice: "Comment was successfully created." }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1 or /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to photo_url(@comment.photo), notice: "Comment was successfully updated." }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1 or /comments/1.json
  def destroy
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to photo_url, notice: "Comment was successfully deleted." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def comment_params
      params.require(:comment).permit(:photo_id, :body, :author_id)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div id="<%= dom_id comment %>">
  <div class="flex space-y-4 items-center">
    <%= link_to person_path(comment.author.id), class: "" do %>
      <div class="my-4">
        <% if comment&.author&.user&.avatar_url&.present? %>
          <figure><img src="<%= comment.author.user.avatar_url.url %>" class="w-12 h-12 md:w-20 md:h-20 object-cover rounded-full" /></figure>
        <% elsif comment&.author&.image_url&.present? %>
          <figure><img src="<%= comment.author.image_url %>" class="w-12 h-12 md:w-20 md:h-20 object-cover rounded-full" /></figure>
        <% else %>
          <div class="w-12 h-12 md:w-20 md:h-20 bg-primary shadow-md border-indigo-500 rounded-full flex items-center justify-center text-lg md:text-2xl font-bold">
            <%= person.first_name.slice(0,1).capitalize %>
          </div>
        <% end %>
      </div>
    <% end %>
    <div class="flex flex-col justify-start space-x-2 ml-4 flex-1">
      <div class="flex justify-between">
        <p class="text-lg font-bold pl-2">
          <%= comment.author.first_name %>
        </p>
        <% if current_user.person.id == comment.author_id %>
          <div class="flex space-x-4">
            <%= link_to image_tag("edit.svg", class: "max-h-[20px]") , edit_comment_path(comment) %>
            <%= button_to comment, method: :delete do %>
              <%= image_tag("trash-can.svg", class: "max-h-[20px]") %>
            <% end %>
          </div>
        <% end %>
      </div>
      <p class="text-lg">
        <%= comment.body %>
      </p>
    </div>
  </div>
</div>

app/views/comments/_form.html.erb
<div class="flex flex-col justify-center items-center">
  <%= simple_form_for(comment) do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
    <div class="form-inputs">
      <%= f.hidden_field :photo_id %>
      <%= f.input :body,
          label: false,
          :as => :text, 
          input_html: { class: "file-input file-input-bordered file-input-primary w-full max-w-xs mt-6 pl-4", rows: 10, cols: 50 } %>
      <%= f.hidden_field :author_id %>
    </div>
    <div class="form-actions flex justify-center mt-12 mb-8">
      <%= f.button :submit, "Add Comment", class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/comments/edit.html.erb
<h1 class="text-center text-2xl mb-4">Edit comment</h1>
<%= render "form", comment: @comment %>
<br>

app/views/comments/index.html.erb
<h1>Comments</h1>
<div id="comments">
  <% @comments.each do |comment| %>
    <%= render comment %>
    <p>
      <%= link_to "Show this comment", comment %>
    </p>
  <% end %>
</div>
<%= link_to "New comment", new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render "form", comment: @comment %>

<br>

<div>
  <%= link_to "Back to comments", comments_path %>
</div>

app/views/comments/show.html.erb
<%= render @comment %>
<div>
  <%= link_to "Edit this comment", edit_comment_path(@comment) %> |
  <%= link_to "Back to comments", comments_path %>
  <%= button_to "Destroy this comment", @comment, method: :delete %>
</div>