config/routes.rb
Rails.application.routes.draw do
  authenticate :user, ->(user) { user.admin? } do
    # I recommend adding indents inside all your blocks
    mount RailsAdmin::Engine, at: "/admin", as: "rails_admin"
  end
  
  resources :recipes
  resources :comments
  resources :photos
  resources :marriages
  resources :people
  resources :filials
  resources :contact_forms, only: [:create]
  devise_for :users, controllers: { registrations: "users/registrations" }

  root "welcome#index"
  get '/family_tree' => 'people#tree', as: :tree
  get "/birthdays" => "people#birthdays", as: :birthdays
  get '/contact_us' => 'contact_forms#contact_us', as: :contact
  get "/family/:id" => "people#family", as: :family
  get "/recipes/my_recipes/:id" => "recipes#my_recipes", as: :my_recipes

end

app/models/person.rb
# == Schema Information
#
# Table name: people
#
#  id             :integer          not null, primary key
#  first_name     :string
#  last_name      :string
#  middle_name    :string
#  maiden_name    :string
#  dob            :string
#  dod            :string
#  place_of_birth :string
#  phone_number   :string
#  address        :string
#  gender         :string
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  suffix         :string
#  image_url      :string
#
class Person < ApplicationRecord
  has_one :user
  has_many :photos, class_name: "Photo", foreign_key: "owner_id", dependent: :destroy

  has_many :parent_relationships, class_name: "Filial", foreign_key: :child_id, dependent: :destroy
  has_many :parents, through: :parent_relationships, source: :parent

  has_many :child_relationships, class_name: "Filial", foreign_key: :parent_id, dependent: :destroy
  has_many :children, through: :child_relationships, source: :child

  has_many :marriages1, class_name: "Marriage", foreign_key: "spouse1_id"
  has_many :spouses1, through: :marriages1, source: :spouse2
  has_many :marriages2, class_name: "Marriage", foreign_key: "spouse2_id"
  has_many :spouses2, through: :marriages2, source: :spouse1

  has_many :people_photos
  has_many :tagged_photos, through: :people_photos, source: :photo

  has_many :comments, class_name: "Comment", foreign_key: "author_id", dependent: :destroy

  has_many :recipes, class_name: "Recipe", foreign_key: "author_id", dependent: :destroy

  def self.ransackable_attributes(auth_object = nil)
    ["first_name"]
  end

  def siblings
    siblings_ids = parents.flat_map { |parent| parent.children.where.not(id: self.id).pluck(:id) }
    Person.where(id: siblings_ids)
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  before_action { authorize(@person || @people || Person) }

  # GET /people or /people.json
  def index
    @people = Person.all
    @q = Person.all.order(first_name: :asc).ransack(params[:q])
    @people = @q.result
  end

  # GET /people/1 or /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people or /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to person_url(@person), notice: "Person was successfully created." }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1 or /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to person_url(@person), notice: "Info was successfully updated." }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1 or /people/1.json
  def destroy
    @person.destroy

    respond_to do |format|
      format.html { redirect_to people_url, notice: "Person was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def tree
    @people = authorize Person.includes(:parents).all
    @main_node = authorize Person.find_by(id: 4) # 4 is the id of the root node i.e. my grandfather
    @children = @main_node.children.sort_by { |child| child.dob.present? ? Date.strptime(child.dob, "%m/%d/%Y").year : Float::INFINITY }
    render "people/family_tree"
  end

  def family  
    @main_node = authorize Person.find_by(id: params[:id])
    render "people/family"
  end

  def birthdays
    current_month = Date.today.strftime("%m")
    @bdays = authorize Person.where("SUBSTR(dob, 1, 2) = ?", current_month).order(Arel.sql("CAST(SUBSTR(dob, 4, 2) AS INTEGER)"))
    render "layouts/birthdays"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def person_params
      params.require(:person).permit(:first_name, :last_name, :middle_name, :maiden_name, :dob, :dod, :place_of_birth, :phone_number, :address, :gender)
    end

end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/people/_bday_list.html.erb
<%# Mobile View card for birthdays %>
<li>
  <%= link_to person_path(person.id), class: "" do %>
    <div class="flex items-center justify-between my-4 mx-1 min-h-[60px]">
      <div class="w-12 bg-slate-600 shadow-xl rounded-full">
        <% if person&.image_url&.present? %>
          <figure><img src="<%= person.image_url %>" class="w-12 h-12 object-cover rounded-full" /></figure>
        <% elsif person&.user&.avatar_url&.present? %>
          <figure><img src="<%= person.user.avatar_url.url %>" class="w-12 h-12 object-cover rounded-full" /></figure>
        <% else %>
          <div class="w-12 h-12 md:w-16 md:h-16 bg-primary shadow-md border-indigo-500 rounded-full flex items-center justify-center text-lg md:text-2xl font-bold">
            <%= person.first_name.slice(0,1).capitalize %>
          </div>
        <% end %>
      </div>
      <div class="grow">
        <h2 class="w-full min-w-[220px] text-center px-4"><%= person.first_name %> <%= person.middle_name %> <%= person.last_name %> <%= person.suffix %></h2>
        <div class="text-center text-xl"><%= person.dob.slice(0,5) %></div>
      </div>
      <div class="mx-auto">
        <%= image_tag("chevron.svg", class: "chevron-image max-h-[25px]", data: { light: asset_path('chevron-black.svg'), dark: asset_path('chevron.svg') }) %>
      </div>
    </div>
  <% end %>
  <% if person.phone_number.present? %>
    <div class="text-center">
      <a href="sms:+1<%= person.phone_number %>?&body=Happy Birthday, <%= person.first_name %>!">
        <button class="btn btn-primary">Text <%= person.first_name %></button>
      </a>
    </div>
  <% end %>
  <% unless index == @bdays.length - 1 %>
    <hr class="flex my-6 mx-auto w-4/5 bg-gray-500">
  <% end %>
</li>

app/views/people/_card.html.erb
<li>
  <div class="flex flex-wrap justify-center items-center w-full">
    <div class="border-indigo-500 flex justify-center my-4">
      <div class="card w-full bg-card-bg shadow-xl border-indigo-500">
        <figure><img src="https://robohash.org/<%= person.id %>" /></figure>
        <div class="card-body border-t-2">
          <h2 class="card-title flex justify-center text-white"><%= person.first_name %> <%= person.middle_name %> <%= person.last_name %> <%= person.suffix %>
          </h2>
          <div class="card-actions justify-center">
            <a href="<%= person_path(person.id) %>"><button class="btn btn-primary">Details</button></a>
          </div>
        </div>
      </div>
    </div>
  </div>
</li>

app/views/people/_family_list.html.erb
<%# This view is individual children of main node in main family tree view %>
<li>
  <%= link_to family_path(person.id), class: "" do %>
    <div class="flex items-center justify-between md:justify-center space-x-4 md:space-x-6 my-4 mx-1">
      <div class="w-14 md:w-24 bg-slate-600 shadow-xl border-indigo-500 rounded-full">
        <% if person&.user&.avatar_url&.present? %>
          <figure><img src="<%= person.user.avatar_url.url %>" class="w-14 h-14 md:w-24 md:h-24 object-cover rounded-full" /></figure>
        <% elsif person&.image_url&.present? %>
          <figure><img src="<%= person.image_url %>" class="w-14 h-14 md:w-24 md:h-24 object-cover rounded-full" /></figure>
        <% else %>
          <div class="w-14 h-14 md:w-24 md:h-24 bg-primary shadow-md border-indigo-500 rounded-full flex items-center justify-center text-lg md:text-2xl font-bold">
            <%= person.first_name.slice(0,1).capitalize %>
          </div>
        <% end %>
      </div>
      <h2 class="w-full max-w-[220px] md:max-w-[340px] md:text-xl"><%= person.first_name %> <%= person.middle_name %> <%= person.last_name %> <%= person.suffix %></h2>
      <div class="items-end">
        <%= image_tag("chevron.svg", class: "chevron-image max-h-[25px]", data: { light: asset_path('chevron-black.svg'), dark: asset_path('chevron.svg') }) %>
      </div>
    </div>
  <% end %>
</li>

app/views/people/_form.html.erb
<div class="flex flex-col items-center border border-slate-700 p-8 rounded-xl mx-4 shadow-lg shadow-indigo-700/40 md:max-w-xl md:mx-auto">
  <%= form_with(model: person) do |form| %>
    <% if person.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(person.errors.count, "error") %> prohibited this person from being saved:</h2>
        <ul>
          <% person.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="space-y-4">
      <div class="md:w-[350px]">
        <%= form.label :first_name, style: "display: block" %>
        <%= form.text_field :first_name, class: "input input-bordered input-primary w-full" %>
      </div>
      <div>
        <%= form.label :last_name, style: "display: block" %>
        <%= form.text_field :last_name, class: "input input-bordered input-primary w-full" %>
      </div>
      <div>
        <%= form.label :middle_name, style: "display: block" %>
        <%= form.text_field :middle_name, class: "input input-bordered input-primary w-full" %>
      </div>
      <div>
        <%= form.label :maiden_name, style: "display: block" %>
        <%= form.text_field :maiden_name, class: "input input-bordered input-primary w-full" %>
      </div>
      <div>
        <%= form.label :dob, "Date of birth (mm/dd/yyyy)", style: "display: block" %>
        <%= form.text_field :dob, class: "input input-bordered input-primary w-full" %>
      </div>
      <div>
        <%= form.label :place_of_birth, style: "display: block" %>
        <%= form.text_field :place_of_birth, class: "input input-bordered input-primary w-full" %>
      </div>
      <div>
        <%= form.label :phone_number, "Phone number (xxx-xxx-xxxx)", style: "display: block" %>
        <%= form.text_field :phone_number, class: "input input-bordered input-primary w-full" %>
      </div>
      <div>
        <%= form.label :address, style: "display: block" %>
        <%= form.text_field :address, id: "address", class: "input input-bordered input-primary w-full" %>
      </div>
      <div class="form-actions flex justify-center">
        <%= form.button "Update", class: "btn btn-primary my-4 shadow-lg shadow-indigo-700/40" %>
      </div>
    <% end %>
  </div>
</div>
<%# Mapbox JS code %>
<script>
  const addressInput = document.getElementById('address');
  const dropdownMenu = document.createElement('div');
  dropdownMenu.setAttribute('id', 'dropdown-menu');
  dropdownMenu.classList.add('hidden', 'w-full', 'bg-gray-800', 'text-white', 'shadow-md', 'rounded-md', 'border', 'border-gray-700', 'space-y-2', 'py-2', 'z-50', 'absolute', 'mt-2', 'max-h-[200px]', 'overflow-auto');
  dropdownMenu.style.width = `${addressInput.offsetWidth}px`;
  addressInput.parentNode.appendChild(dropdownMenu);
  // indentation helps readability
  addressInput.addEventListener('input', (event) => {
    const query = event.target.value;
    fetch(`https://api.mapbox.com/geocoding/v5/mapbox.places/${query}.json?access_token=<%= ENV['MAPBOX_TOKEN'] %>`)
      .then(response => response.json())
      .then(data => {
        dropdownMenu.innerHTML = '';
      if (data.features.length > 0) {
        dropdownMenu.classList.remove('hidden');
      } else {
        dropdownMenu.classList.add('hidden');
      }
      data.features.forEach(feature => {
      const option = document.createElement('div');
      option.textContent = feature.place_name;
      option.classList.add('px-4', 'py-2', 'hover:bg-indigo-500', 'hover:text-white', 'cursor-pointer');
      option.addEventListener('click', () => {
        addressInput.value = feature.place_name;
        dropdownMenu.innerHTML = '';
        dropdownMenu.classList.add('hidden');
      });
        dropdownMenu.appendChild(option);
      });
    });
  });
</script>

app/views/people/_list.html.erb
<%# Great partials! %>
<%# This view is the main node for each individual family i.e. Eduardo %>
<li class="md:w-[600px]">
  <%= link_to person_path(person.id), class: "" do %>
    <div class="flex items-center justify-between md:justify-center space-x-4 md:space-x-6 my-4 mx-1 min-h-[60px]">
      <div class="w-14 md:w-24 bg-slate-600 shadow-xl border-indigo-500 rounded-full">
        <% if person&.user&.avatar_url&.present? %>
          <figure><img src="<%= person.user.avatar_url.url %>" class="w-14 h-14 md:w-24 md:h-24 object-cover rounded-full" /></figure>
        <% elsif person&.image_url&.present? %>
          <figure><img src="<%= person.image_url %>" class="w-14 h-14 md:w-24 md:h-24 object-cover rounded-full" /></figure>
        <% else %>
          <div class="w-14 h-14 md:w-24 md:h-24 bg-primary shadow-md border-indigo-500 rounded-full flex items-center justify-center text-lg md:text-2xl font-bold">
            <%= person.first_name.slice(0,1).capitalize %>
          </div>
        <% end %>
      </div>
      <h2 class="w-full max-w-[220px] md:max-w-[340px] md:text-xl"><%= person.first_name %> <%= person.middle_name %> <%= person.last_name %> <%= person.suffix %></h2>
      <div class="items-end">
        <%= image_tag("chevron.svg", class: "chevron-image max-h-[25px]", data: { light: asset_path('chevron-black.svg'), dark: asset_path('chevron.svg') }) %>
      </div>
    </div>
  <% end %>
</li>

app/views/people/_person.html.erb
<%# This is the view for individual people, mobile view is at the bottom i.e. their profile page %>
<%# Desktop View %>
<div class="hidden md:w-3/4 md:flex md:justify-center md:items-center md:mx-auto md:mb-16">
  <div class="flex justify-center m-4">
    <div class="card w-[400px] dark:bg-slate-700 shadow-xl">
      <% if person&.user&.avatar_url&.present? %>
        <figure><img src="<%= person.user.avatar_url %>" /></figure>
      <% elsif person&.image_url&.present? %>
        <figure><img src="<%= person.image_url %>" /></figure>
      <% else %>
        <div class="h-[300px] bg-primary shadow-md border-indigo-500 flex rounded-t-xl items-center justify-center text-7xl font-bold">
          <%= person.first_name.slice(0,1).capitalize %>
        </div>
      <% end %>
      <div class="card-body flex flex-col items-center border-t-2">
        <h2 class="card-title text-white text-center"><%= person.first_name %> <%= person.middle_name %> <%= person.last_name %> <%= person.suffix %></h2>
        <h4 class="text-xl">Birthdate</h4>
        <p class="text-white"><%= person.dob %></p>
        <% if person.place_of_birth.present? %>
          <h4 class="text-xl">Birthplace</h4>
          <p class="text-white"><%= person.place_of_birth %></p>
        <% end %>
        <% if person.address.present? %>
          <h4 class="text-xl">Address</h4>
          <p class="text-white text-center max-w-[180px]"><%= person.address %></p>
        <% end %>
        <% if person.user&.email.present? %>
          <h4 class="text-xl">Email</h4>
          <p class=" text-center max-w-[180px]"><%= person.user.email %></p>
        <% end %>
        <% if person.phone_number.present? %>
          <h4 class="text-xl">Phone Number</h4>
          <p class=""><%= person.phone_number %></p>
          <a href="sms:+1<%= person.phone_number %>?&body=Hi <%= person.first_name %>!">
            <button class="btn btn-primary">Text <%= person.first_name %></button>
          </a>
        <% end %>
        <hr class="w-full">
        <% if !person.parents.first.nil? %>
          <h2 class="text-2xl">Parents:</h2>
          <% person.parents.each do |parent| %>
            <a href="<%= parent.id %>">
              <p class="text-white text-center"> <%= parent.first_name %> <%= parent.middle_name %> <%= parent.last_name %> <%= parent.suffix %></p>
            </a>
          <% end %>
        <% end %>
        <% if !person.siblings.first.nil? %>
          <h2 class="text-2xl">Siblings:</h2>
          <% person.siblings.each do |sibling| %>
            <a href="<%= sibling.id %>">
              <p class="text-white text-center"> <%= sibling.first_name %> <%= sibling.middle_name %> <%= sibling.last_name %> <%= sibling.suffix %></p>
            </a>
          <% end %>
        <% end %>
        <% if !person.spouses1.first.nil? || !person.spouses2.first.nil? %>
          <h2 class="text-2xl">Spouse:</h2>
          <% person.spouses1.each do |spouse| %>
            <a href="<%= spouse.id %>">
              <p class="text-white text-center"><%= spouse.first_name %> <%= spouse.middle_name %> <%= spouse.last_name %> <%= spouse.suffix %></p>
            </a>
          <% end %>
          <% person.spouses2.each do |spouse| %>
            <a href="<%= spouse.id %>">
              <p class="text-white text-center"><%= spouse.first_name %> <%= spouse.middle_name %> <%= spouse.last_name %> <%= spouse.suffix %></p>
            </a>
          <% end %>
        <% end %>
        <% if !person.children.first.nil? %>
          <h2 class="text-2xl">Children:</h2>
          <% person.children.each do |child| %>
            <a href="<%= child.id %>">
              <p class="text-white text-center"><%= child.first_name %> <%= child.middle_name %> <%= child.last_name %> <%= child.suffix %></p>
            </a>
          <% end %>
        <% end %>
      </div>
    </div>
    <div class="flex flex-col ml-8">
      <% if person.tagged_photos.any? %>
        <h2 class="text-2xl text-center mb-8 font-medium">Tagged Photos:</h2>
        <div class="flex flex-wrap justify-start mb-16">
          <% person.tagged_photos.order(created_at: :desc).each do |photo| %>
            <div class="min-w-32 min-h-32 overflow-hidden border border-black">
              <%= link_to photo_path(photo) do %>
                <img src="<%= photo.image_url %>" alt="Photo" class="object-cover w-32 h-32">
              <% end %>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>
<%# Mobile View %>
<div class="block md:hidden mb-4">
  <div class="flex items-center justify-center space-x-2 my-12 mx-1">
    <div class="w-32 h-32 bg-slate-600 shadow-xl border-indigo-500 rounded-full">
      <% if person&.user&.avatar_url&.present? %>
        <figure><img src="<%= person.user.avatar_url %>" class="w-32 h-32 object-cover rounded-full" /></figure>
      <% elsif person&.image_url&.present? %>
        <figure><img src="<%= person.image_url%>" class="w-32 h-32 object-cover rounded-full" /></figure>
      <% else %>
        <div class="w-32 h-32 bg-primary shadow-md border-indigo-500 rounded-full flex items-center justify-center text-5xl font-bold">
          <%= person.first_name.slice(0,1).capitalize %>
        </div>
      <% end %>
    </div>
  </div>
  <h2 class="w-full text-center text-2xl"><%= person.first_name %> <%= person.middle_name %> <%= person.last_name %> <%= person.suffix %></h2>
  <div tabindex="0" class="collapse border w-4/5 border-base-300 bg-base-200 mx-auto mt-12">
    <div class="collapse-title text-xl text-center font-medium ml-4">
      Click for info
    </div>
    <div class="collapse-content">
      <div class="card-body flex flex-col items-center border-t-2">
        <h4 class="text-2xl font-medium">Birthdate</h4>
        <p class="text-lg"><%= person.dob %></p>
        <% if person.place_of_birth.present? %>
          <h4 class="text-2xl font-medium">Birthplace</h4>
          <p class="text-lg"><%= person.place_of_birth %></p>
        <% end %>
        <% if person.address.present? %>
          <h4 class="text-2xl font-medium">Address</h4>
          <p class=" text-center max-w-[180px]"><%= person.address %></p>
        <% end %>
        <% if person.user&.email.present? %>
          <h4 class="text-2xl font-medium">Email</h4>
          <p class="text-lg text-center max-w-[180px]"><%= person.user.email %></p>
        <% end %>
        <% if person.phone_number.present? %>
          <h4 class="text-2xl font-medium">Phone Number</h4>
          <p class="text-lg"><%= person.phone_number %></p>
          <a href="sms:+1<%= person.phone_number %>?&body=Hi <%= person.first_name %>!">
            <button class="btn btn-primary">Text <%= person.first_name %></button>
          </a>
        <% end %>
        <hr class="w-full my-4">
        <% if !person.parents.first.nil? %>
          <h2 class="text-2xl font-medium">Parents:</h2>
          <% person.parents.each do |parent| %>
            <a href="<%= parent.id %>">
              <p class="text-center"> <%= parent.first_name %> <%= parent.middle_name %> <%= parent.last_name %> <%= parent.suffix %></p>
            </a>
          <% end %>
        <% end %>
        <% if !person.siblings.first.nil? %>
          <h2 class="text-2xl font-medium">Siblings:</h2>
          <% person.siblings.each do |sibling| %>
            <a href="<%= sibling.id %>">
              <p class="text-center"> <%= sibling.first_name %> <%= sibling.middle_name %> <%= sibling.last_name %> <%= sibling.suffix %></p>
            </a>
          <% end %>
        <% end %>
        <% if !person.spouses1.first.nil? || !person.spouses2.first.nil? %>
          <h2 class="text-2xl font-medium">Spouse:</h2>
          <% person.spouses1.each do |spouse| %>
            <a href="<%= spouse.id %>">
              <p class="text-center"><%= spouse.first_name %> <%= spouse.middle_name %> <%= spouse.last_name %> <%= spouse.suffix %></p>
            </a>
          <% end %>
          <% person.spouses2.each do |spouse| %>
            <a href="<%= spouse.id %>">
              <p class="text-center"><%= spouse.first_name %> <%= spouse.middle_name %> <%= spouse.last_name %> <%= spouse.suffix %></p>
            </a>
          <% end %>
        <% end %>
        <% if !person.children.first.nil? %>
          <h2 class="text-2xl font-medium">Children:</h2>
          <% person.children.each do |child| %>
            <a href="<%= child.id %>">
              <p class="text-center"><%= child.first_name %> <%= child.middle_name %> <%= child.last_name %> <%= child.suffix %></p>
            </a>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
  <% if person.recipes.present? %>
    <div class="text-center my-8">
      <%= link_to "My Recipes", my_recipes_path(person.id), class: "btn btn-primary" %>
    </div>
  <% end %>
  <% if person.tagged_photos.any? %>
    <h2 class="text-2xl text-center my-8">Tagged Photos:</h2>
    <div class="flex flex-wrap justify-start max-w-[390px] mb-16 mx-auto">
      <% person.tagged_photos.order(created_at: :desc).each do |photo| %>
        <div class="min-w-32 min-h-32 overflow-hidden border border-black">
          <%= link_to photo_path(photo) do %>
            <img src="<%= photo.image_url %>" alt="Photo" class="object-cover w-32 h-32">
          <% end %>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/people/_tree_person.html.erb
<%# This view is individual families i.e. Salvador's Family %>
<div class="<%= 'border border-slate-700 p-2 max-w-5xl' unless person.parents.any? { |parent| parent.parents.include?(@main_node) } %>">
  <li>
    <%= render "list", person: person %>
    <% if person.spouses1.any? %>
      <div class="flex justify-center items-center">
        <%= image_tag ("marriage.svg"), class: "max-h-[40px] md:max-h-[60px]" %>
      </div>
      <% person.spouses1.each do |spouse| %>
        <%= render "list", person: spouse %>
      <% end %>
    <% end %>
    <% if person.spouses2.any? %>
      <div class="flex justify-center items-center">
        <%= image_tag ("marriage.svg"), class: "max-h-[40px] md:max-h-[60px]" %>
      </div>
      <% person.spouses2.each do |spouse| %>
        <%= render "list", person: spouse %>
      <% end %>
    <% end %>
    <% if person.children.any? %>
      <li class="text-xl text-center pb-2">Children</li>
      <% person.children.each do |child| %>
        <%= render "tree_person", person: child %>
      <% end %>
    <% end %>
  </li>
</div>

app/views/people/edit.html.erb
<h1 class="text-center text-2xl my-4">Edit personal info</h1>
<%= render "form", person: @person %>
<br>

app/views/people/index.html.erb
<%# This file is used for the search function on the site %>
<h1 class="text-2xl md:text-4xl text-center my-4">Family Members</h1>
<%= search_form_for @q do |f| %>
  <div class="flex flex-col items-center justify-center mb-4 mx-4 md:w-2/5 md:mx-auto">
    <div class="form-control w-full flex flex-col justify-center items-center border border-slate-700 p-8 rounded-xl space-y-4 shadow-lg shadow-indigo-700/40 mb-8">
      <%= f.label :first_name_cont, "First name containing" %>
      <%= f.text_field :first_name_cont, class: "input input-bordered input-primary w-full max-w-xs placeholder:text-slate-600", :placeholder => "Enter a few characters" %>
    </div>
    <%= f.submit :class => "btn btn-primary" %>
    <button class="btn btn-ghost"><a href="/people">Clear filters</a></button>
  <% end %>
</div>
<div id="people" class="flex items-center justify-center mb-16">
  <ul class="flex flex-col justify-center w-full space-y-2">
    <% @people.each do |person| %>
      <li class="">
        <%= link_to person_path(person.id), class: "" do %>
          <div class="flex items-center justify-center space-x-4 md:space-x-6 my-4 mx-1 min-h-[60px] md:w-1/2 md:mx-auto">
            <div class="w-14 md:w-24 bg-slate-600 shadow-xl rounded-full">
              <% if person&.user&.avatar_url&.present? %>
                <figure><img src="<%= person.user.avatar_url %>" class="w-14 h-14 md:w-24 md:h-24 object-cover rounded-full" /></figure>
              <% elsif person&.image_url&.present? %>
                <figure><img src="<%= person.image_url %>" class="w-14 h-14 md:w-24 md:h-24 object-cover rounded-full" /></figure>
              <% else %>
                <div class="w-14 h-14 md:w-24 md:h-24 bg-primary shadow-md border-indigo-500 rounded-full flex items-center justify-center text-lg md:text-2xl font-bold">
                  <%= person.first_name.slice(0,1).capitalize %>
                </div>
              <% end %>
            </div>
            <h2 class="w-full max-w-[220px] md:max-w-[380px] pl-4 grow md:text-2xl"><%= person.first_name %> <%= person.middle_name %> <%= person.last_name %> <%= person.suffix %></h2>
            <%= image_tag("chevron.svg", class: "chevron-image max-h-[25px]", data: { light: asset_path('chevron-black.svg'), dark: asset_path('chevron.svg') }) %>
          </div>
        <% end %>
      </li>
    <% end %>
  </ul>
</div>

app/views/people/show.html.erb
<%= render @person %>