config/routes.rb
Rails.application.routes.draw do
  authenticate :user, ->(user) { user.admin? } do
    # I recommend adding indents inside all your blocks
    mount RailsAdmin::Engine, at: "/admin", as: "rails_admin"
  end
  
  resources :recipes
  resources :comments
  resources :photos
  resources :marriages
  resources :people
  resources :filials
  resources :contact_forms, only: [:create]
  devise_for :users, controllers: { registrations: "users/registrations" }

  root "welcome#index"
  get '/family_tree' => 'people#tree', as: :tree
  get "/birthdays" => "people#birthdays", as: :birthdays
  get '/contact_us' => 'contact_forms#contact_us', as: :contact
  get "/family/:id" => "people#family", as: :family
  get "/recipes/my_recipes/:id" => "recipes#my_recipes", as: :my_recipes

end

app/models/photo.rb
# == Schema Information
#
# Table name: photos
#
#  id         :integer          not null, primary key
#  owner_id   :integer
#  image_url  :string
#  caption    :string
#  location   :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Photo < ApplicationRecord
    validates_presence_of :image_url, :caption
    
    belongs_to :owner, class_name: "Person", foreign_key: "owner_id"
    has_many :people_photos, dependent: :destroy
    has_many :people, through: :people_photos

    has_many :comments, class_name: "Comment", foreign_key: "photo_id", dependent: :destroy

    mount_uploader :image_url, ImageUrlUploader
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  before_action { authorize(@photo || Photo) }
  

  # GET /photos or /photos.json
  def index
  @pagy, @photos = pagy(Photo.all.order(created_at: :desc), items: 45)

  end

  # GET /photos/1 or /photos/1.json
  def show
  @photo = Photo.find(params[:id])
  @download_url = Cloudinary::Utils.private_download_url(@photo.image_url.file.public_id, @photo.image_url.file.format, attachment: true)

end

  # GET /photos/new
  def new
    @photo = Photo.new
    @people = Person.all
  end

  # GET /photos/1/edit
  def edit
  end

  # POST /photos or /photos.json
def create
  @photo = Photo.new(photo_params)
  @photo.owner_id = current_user.person.id

  respond_to do |format|
    if @photo.save
      format.html { redirect_to photo_url(@photo), notice: "Photo was successfully created." }
      format.json { render :show, status: :created, location: @photo }
    else
      format.html { render :new, status: :unprocessable_entity }
      format.json { render json: @photo.errors, status: :unprocessable_entity }
    end
  end
end

  # PATCH/PUT /photos/1 or /photos/1.json
  def update
    @photo
    respond_to do |format|
      if @photo.update(photo_params)
        format.html { redirect_to photo_url(@photo), notice: "Photo was successfully updated." }
        format.json { render :show, status: :ok, location: @photo }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1 or /photos/1.json
  def destroy
    @photo.destroy

    respond_to do |format|
      format.html { redirect_to photos_url, notice: "Photo was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_photo
      @photo = Photo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def photo_params
      params.require(:photo).permit(:owner_id, :image_url, :caption, :location, { person_ids: [] })
    end


end

app/helpers/photos_helper.rb
module PhotosHelper
    include Pagy::Frontend
end

app/views/photos/_form.html.erb
<%= simple_form_for(@photo) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
  <div class="flex justify-center">
    <div class="form-control w-full max-w-sm mx-4 border border-slate-600 shadow-lg shadow-indigo-700/40 p-4 rounded-xl space-y-12">
      <%= f.hidden_field :owner_id, 
              input_html: { value: current_user.id } %>
      <%= f.input :image_url,
              label: "Choose an image",
              as: :file,
              input_html: { class: "file-input file-input-bordered file-input-primary w-full max-w-xs" } %>
      <%= f.input :caption,
              input_html: { class: "file-input file-input-bordered file-input-primary w-full max-w-xs pl-4" } %>
      <%= f.input :location,
              input_html: { class: "file-input file-input-bordered file-input-primary w-full max-w-xs pl-4" } %>
      <div class="flex flex-col items-center justify-center space-y-2">
        <%= f.label :person_ids, "Tag People", class: "text-xl" %>
        <%= f.select :person_ids, Person.all.order(:first_name).map { |p| ["#{p.first_name} #{p.last_name} #{p.suffix}", p.id] }, {}, { multiple: true, class: "select2 select select-bordered select-primary w-full max-w-xs" } %>
      </div>
      <div class="form-actions flex justify-center">
        <%= f.button :submit, "Upload Photo", class: "btn btn-primary my-4" %>
      </div>
    </div>
  </div>
<% end %>
<script>
  // JS code for select2 dropdown menu for tagging people
  $(document).ready(function() {
  $('.select2').select2({
    theme: 'classic',
  });
  });
</script>

app/views/photos/_photo.html.erb
<%# Main view file for all photos that are uploaded %>
<div id="<%= dom_id photo %>" class="flex flex-col items-center justify-center md:w-1/2 mx-auto">
  <div class="flex justify-between mb-2 mx-4 mt-4 w-full">
    <div class="flex space-x-2 md:w-[450px]">
      <%= link_to person_path(photo.owner.id), class: "" do %>
        <div class="h-12 w-12 rounded-full overflow-hidden ml-4">
          <%= image_tag(photo.owner.user.avatar_url.url, class: "h-full w-full object-cover") %>
        </div>
      <% end %>
      <div>
        <p>
          <%= photo.owner.first_name %> <%= photo.owner.last_name %> <%= photo.owner.suffix %>
        </p>
        <% if photo.location.present? %>
          <p class="text-sm">
            <%= photo.location %>
          </p>
        <% end %>
      </div>
    </div>
    <div class="flex items-center md:w-full md:justify-end space-x-4 mr-4">
      <% if current_user.person.id != @photo.owner_id %>
        <%= link_to image_tag("download.svg", class: "max-h-[20px]"), photo.image_url.url, download: '' %>
      <% end %>
      <% if current_user.person.id == @photo.owner_id %>
        <div class="flex space-x-4">
          <%= link_to image_tag("edit.svg", class: "max-h-[20px]"), edit_photo_path(@photo) %>
          <%= button_to @photo, method: :delete do %>
            <%= image_tag("trash-can.svg", class: "max-h-[20px]") %>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
  <div class="w-full flex justify-center">
    <img src="<%= photo.image_url.url %>" class="">
  </div>
  <div>
    <% if photo.people.present? %>
      <div class="flex flex-col items-center space-y-2 mt-4">
        <p>People tagged in this photo:</p>
        <div class="flex flex-wrap space-x-2">
          <% photo.people.each do |person| %>
            <% if person&.image_url&.present? %>
              <div class="w-10 md:w-16 rounded-full">
                <%= link_to person_path(person.id), class: "" do %>
                  <img src="<%= person.image_url %>" alt="<%= person.first_name %>'s avatar" class="w-10 h-10 md:w-16 md:h-16 object-cover rounded-full">
                <% end %>
              </div>
            <% elsif person&.user&.avatar_url&.url.present? %>
              <div class="w-10 md:w-16 rounded-full">
                <%= link_to person_path(person.id), class: "" do %>
                  <img src="<%= person&.user&.avatar_url&.url %>" alt="<%= person.first_name %>'s avatar" class="w-10 h-10 md:w-16 md:h-16 object-cover rounded-full">
                <% end %>
              </div>
            <% else %>
              <div class="w-10 h-10 md:w-16 md:h-16 bg-primary shadow-xl border-indigo-500 rounded-full flex items-center justify-center text-lg md:text-2xl font-bold">
                <%= link_to person_path(person.id), class: "" do %>
                  <%= person.first_name.slice(0,1).capitalize %>
                <% end %>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
    <% end %>
    <div class="flex flex-col justify-center p-4 mt-2 w-full">
      <p class="text-lg mb-8">
        <%= photo.caption %>
      </p>
      <% if photo.comments.present? %>
        <% photo.comments.each do |comment| %>
          <%= render "comments/comment", comment: comment %>
        <% end %>
      <% end %>
      <p class="text-sm my-6"><%= photo.created_at.strftime("%B %d, %Y") %></p>
      <div class="">
        <%= render "comments/form", comment: Comment.new(photo_id: photo.id, author_id: current_user.person.id) %>
      </div>
    </div>
  </div>

app/views/photos/edit.html.erb
<h1 class="text-center text-2xl mb-4">Edit photo</h1>
<%= render "form", photo: @photo %>
<br>

app/views/photos/index.html.erb
<h1 class="text-3xl text-white mx-auto my-8 text-center">Photos</h1>
<div class="text-xl text-white mx-auto my-8 text-center">
  <%= button_to "+ Upload a new photo", new_photo_path, method: :get, class: "btn btn-primary" %>
</div>
<div id="photos" class="flex flex-wrap justify-start max-w-[385px] md:max-w-[650px] mb-16 mx-auto">
  <% @photos.each do |photo| %>
    <div id="<%= dom_id photo %>" class="overflow-hidden border border-black h-32 w-32">
      <%= link_to photo_path(photo) do %>
        <img src="<%= photo.image_url.url %>" class="object-cover w-32 h-32">
      <% end %>
    </div>
  <% end %>
</div>
<div class="flex justify-center mb-16">
  <%== pagy_nav(@pagy) %>
</div>
</div>

app/views/photos/new.html.erb
<h1 class="text-3xl text-white mx-auto my-8 text-center">Upload a photo</h1>
<%= render "form", photo: @photo %>
<br>

app/views/photos/show.html.erb
<%= render @photo %>
<div class="my-8">
  <%= link_to "Back to photos", photos_path, class: "btn btn-ghost-outline" %>
</div>