config/routes.rb
Rails.application.routes.draw do
  authenticate :user, ->(user) { user.admin? } do
    # I recommend adding indents inside all your blocks
    mount RailsAdmin::Engine, at: "/admin", as: "rails_admin"
  end
  
  resources :recipes
  resources :comments
  resources :photos
  resources :marriages
  resources :people
  resources :filials
  resources :contact_forms, only: [:create]
  devise_for :users, controllers: { registrations: "users/registrations" }

  root "welcome#index"
  get '/family_tree' => 'people#tree', as: :tree
  get "/birthdays" => "people#birthdays", as: :birthdays
  get '/contact_us' => 'contact_forms#contact_us', as: :contact
  get "/family/:id" => "people#family", as: :family
  get "/recipes/my_recipes/:id" => "recipes#my_recipes", as: :my_recipes

end

app/views/layouts/_footer.html.erb
<footer class="footer py-10 bg-base-200 text-base-content w-full">
  <div class="stat flex justify-center items-center">
    <div class="stat-value text-primary"><%= User.all.count %></div>
    <div class="stat-title">Family Members Signed Up</div>
  </div>
  <div class="flex w-full justify-around">
    <nav class="flex flex-col space-y-2">
      <header class="footer-title">Links</header>
      <%= link_to "Family Tree", tree_path %>
      <%= link_to "Photos", photos_path %>
      <%= link_to "Birthdays", birthdays_path %>
      <%= link_to "Recipes", recipes_path %>
    </nav>
    <nav class="flex flex-col space-y-2">
      <header class="footer-title">Extras</header>
      <%= link_to "Search", people_path %>
      <%= link_to "Contact Us", contact_path %>
    </nav>
  </div>
  <div class="flex flex-col w-full items-center justify-center">
    <h2>Designed by</h2>
    <aside>
      <a href="http://www.nemin.dev" target="_blank"><%= image_tag ("nemdev.png"), class: "max-h-[60px] rounded-full" %></a>
    </aside>
  </div>
</footer>

app/views/layouts/_header.html.erb
<div class="navbar bg-base-200 min-h-[80px]">
  <div class="flex-1 rounded-full">
    <a href="<%= root_path %>" class=""><%= image_tag ("tilde.png"), class: "rounded-full h-[65px] w-[65px] md:max-h-[80px] object-fill p-2" %> </a>
  </div>
  <div class="flex flex-row-reverse md:flex-row items-center">
    <% if user_signed_in? %>
      <div class="menu-trigger md:hidden">
        <button class="btn btn-ghost normal-case text-xl mr-4" onclick="toggleDropdown(this);">
          <%= image_tag("burger-menu.svg", id: "burger-menu", class: "max-h-[40px] fill-white", data: { light: asset_path('burger-menu-black.svg'), dark: asset_path('burger-menu.svg'), close_light: asset_path('close-black.svg'), close_dark: asset_path('close.svg') }) %>
        </button>
      </div>
    <% end %>
    <ul id="dropdown-menu" class="hidden md:flex md:items-center menu menu-horizontal px-1 mr-4">
      <li><%= link_to "Family Tree", tree_path %></li>
      <li><%= link_to "Photos", photos_path %></li>
      <li><%= link_to "Birthdays", birthdays_path %></li>
      <li><%= link_to "Recipes", recipes_path %></li>
      <li><%= link_to "Search", people_path %></li>
      <li><%= image_tag(asset_path("sun.svg"), id: "mode-display", class: "w-16 h-16", onclick: "toggleMode()", data: { light: asset_path('moon.svg'), dark: asset_path('sun.svg') }) %></li>
    </ul>
    <% if user_signed_in? %>
      <p class="hidden md:block pr-4"><%= current_user.email %></p>
      <div class="dropdown dropdown-end pr-4">
        <label tabindex="0" class="btn btn-primary btn-circle avatar">
          <div id="avatar_container" class="w-10 rounded-full">
            <% if current_user.avatar_url.present? %>
              <%= image_tag(current_user.avatar_url.url, id: "avatar_image") %>
            <% else %>
              <div class="w-12 h-12 bg-primary shadow-md border-indigo-500 rounded-full flex items-center justify-center text-xl font-bold">
                <%= current_user.person.first_name.slice(0,1).capitalize %>
              </div>
            <% end %>
          </div>
        </label>
        <ul tabindex="0" class="mt-3 z-[1] p-2 shadow menu menu-sm dropdown-content bg-base-100 rounded-box w-52 space-y-2">
          <li>
            <% if current_user.person.present? %>
              <%= link_to "My Profile", person_path(current_user.person.id) %>
            <% end %>
          </li>
          <li><%= link_to "Edit personal info", edit_person_path(current_user.person.id) %></li>
          <li><%= link_to "Edit login info", edit_user_registration_path %></li>
          <li>
            <% if current_user.admin? %>
              <%= link_to "Admin Dashboard", rails_admin_path %>
            <% end %>
          </li>
          <li><%= link_to "Sign Out", destroy_user_session_path, data: { turbo_method: :delete } %></li>
        </ul>
      </div>
    <% else %>
      <ul class="flex space-x-4">
        <li><%= link_to "Sign In", new_user_session_path, class: "btn btn-primary" %></li>
        <li><%= link_to "Sign Up", new_user_registration_path, class: "btn btn-primary mr-2" %></li>
      </ul>
    <% end %>
  </div>
</div>
<script>
  // JS code for the dropdown menu
  var isDropdownOpen = false;

  function toggleDropdown(button) {
    var dropdown = document.getElementById("dropdown-menu");
    var avatarContainer = document.getElementById("avatar_container");
    var image = button.querySelector('img');
    var currentMode = document.body.getAttribute('data-theme');
    if (isDropdownOpen) {
      dropdown.style.display = "none";
      avatarContainer.classList.remove('hidden');
      var newSrc = image.getAttribute('data-' + currentMode); // burger-menu.svg or burger-menu-black.svg
    if (newSrc) {
      image.src = newSrc;
      }
    isDropdownOpen = false;
    }
    else {
      dropdown.style.display = "block";
      avatarContainer.classList.add('hidden');
      var newSrc = image.getAttribute('data-close-' + currentMode); // close.svg or close-black.svg
    if (newSrc) {
      image.src = newSrc;
      }
    isDropdownOpen = true;
    }
  }

  // JS code for light/dark mode toggle
  function toggleMode() {
    var body = document.body;
    var currentMode = body.getAttribute('data-theme');
    var newMode = currentMode === 'light' ? 'dark' : 'light';
    body.setAttribute('data-theme', newMode);
    var modeDisplayImage = document.getElementById('mode-display');
    var newSrc = modeDisplayImage.getAttribute('data-' + newMode);
    if (newSrc) {
      modeDisplayImage.src = newSrc;
    }
      localStorage.setItem('theme', newMode);
  }
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Family Tree</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="icon" type="image/x-icon" href="<%= asset_path("favicon.ico") %>" >
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100;300;400;500;700;800&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <script>
      document.documentElement.setAttribute('data-theme', window.localStorage.getItem('theme'))
    </script>
    <script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
  </head>
  <body>
    <%= render "layouts/header" %>
    <% if notice %>
      <div class="flex justify-center items-center mt-4">
        <p class="alert alert-success w-[340px]"><%= notice %></p>
      </div>
    <% end %>
    <% if alert %>
      <div class="flex justify-center items-center mt-4">
        <p class="alert alert-error w-[340px]"><%= alert %></p>
      </div>
    <% end %>
    <%= yield %>
    <%= render "layouts/footer" %>
    <script
    id="search-js"
    defer
    src="https://api.mapbox.com/search-js/v1.0.0-beta.18/web.js"
></script>
    <script>
      document.addEventListener('turbo:load', function() {
        var savedTheme = localStorage.getItem('theme');
        if(savedTheme) {
          document.body.setAttribute('data-theme', savedTheme);
          var modeDisplayImage = document.getElementById('mode-display');
          if(modeDisplayImage) {
            modeDisplayImage.src = modeDisplayImage.getAttribute('data-' + savedTheme);
          }
          var burgerMenuImage = document.getElementById('burger-menu');
          if(burgerMenuImage) {
            burgerMenuImage.src = burgerMenuImage.getAttribute('data-' + savedTheme);
          }
          var chevronImages = document.getElementsByClassName('chevron-image');
          for(var i = 0; i < chevronImages.length; i++) {
            var newSrc = chevronImages[i].getAttribute('data-' + savedTheme);
            if(newSrc) {
              chevronImages[i].src = newSrc;
            }
          }
        }
      });
    </script>
  </body>
</html>

app/views/layouts/birthdays.html.erb
<%# This view is the main birthday view %>
<%# Desktop View %>
<div class="hidden md:block md:mb-16">
  <h1 class="text-5xl mx-auto my-12 text-center">Birthdays this Month 🎂</h1>
  <div class="flex flex-wrap justify-center items-center w-3/4 mx-auto">
    <% @bdays.each do |person| %>
      <div class="m-8">
        <div class="card w-[350px] max-h-[550px] dark:bg-slate-700 shadow-xl">
          <% if person&.user&.avatar_url&.present? %>
            <figure><img src="<%= person.user.avatar_url.url %>" /></figure>
          <% elsif person&.image_url&.present? %>
            <figure><img src="<%= person.image_url %>" /></figure>
          <% else %>
            <div class="h-[300px] bg-primary shadow-md border-indigo-500 rounded-t-xl flex items-center justify-center text-7xl font-bold">
              <%= person.first_name.slice(0,1).capitalize %>
            </div>
          <% end %>
          <div class="card-body border-t-2">
            <h2 class="card-title text-white text-center justify-center"><%= person.first_name %> <%= person.middle_name %> <%= person.last_name %> <%= person.suffix %></h2>
            <h3 class="card-body justify-center text-center text-xl text-white"><%= person.dob.slice(0,5) %> </h3>
            <div class="card-actions justify-center">
              <a href="<%= person_path(person.id) %>"><button class="btn btn-primary">Details</button></a>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </ul>
</div>
</div>
<%# Mobile View %>
<div class="md:hidden my-16">
  <div class="text-6xl mx-auto text-center">🎂</div>
  <h1 class="text-3xl m-auto my-8 text-center">Birthdays this Month</h1>
  <div class="px-4 max-w-5xl m-auto">
    <ul class="border border-slate-700 px-2 py-6 rounded overflow-hidden shadow-md">
      <% @bdays.each_with_index do |person, index| %>
        <%= render "bday_list", person: person, index: index %>
      <% end %>
    </ul>
  </div>
</div>

app/views/layouts/contact_us.html.erb
<div class="mx-4 mb-6 md:max-w-sm md:mx-auto">
  <h1 class="text-3xl text-white mx-auto my-8 text-center">Contact Us</h1>
  <p class="text-center">Let me know what you think of the site. If something is not working correctly or broken please let me know so I can fix it. If there is a feature you would like to see shoot me a message and I can see about integrating it.</p>
</div>
<%= form_with(model: @contact, url: contact_forms_path, data: { turbo: false }) do |form| %>
  <div class="flex justify-center mb-16 mx-4">
    <div class="form-control w-full max-w-sm border border-slate-700 p-8 rounded-xl space-y-12 shadow-lg shadow-indigo-700/40">
      <div>
        <%= form.label :name %>
        <%= form.text_field :name, class: "input input-bordered input-primary w-full max-w-xs placeholder:text-slate-600" %>
      </div>
      <div>
        <%= form.label :email %>
        <%= form.text_field :email, class: "input input-bordered input-primary w-full max-w-xs placeholder:text-slate-600" %>
      </div>
      <div>
        <%= form.label :message %>
        <%= form.text_area :message, class: "input input-bordered input-primary w-full h-40 max-w-xs placeholder:text-slate-600"  %>
      </div>
      <div class='flex justify-center'>
        <%= recaptcha_tags %>
      </div>
      <div class="form-actions flex justify-center">
        <%= form.button "Send", class: "btn btn-primary my-4 shadow-lg shadow-indigo-700/40" %>
      </div>
    </div>
  <% end %>
</div>